version: 2
updates:
  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for the nuget packages.
  - package-ecosystem: "nuget"
    directory: "/src/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
