version: 2
updates:
  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
  # Maintain dependencies for the nuget packages.
  - package-ecosystem: "nuget"
    directory: "/src/StellarApi"
    schedule:
      interval: "daily"
    target-branch: "develop"
    open-pull-requests-limit: 25
