# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & deploy .NET APP

on: [push]

env:
  stellar_image: '${{ secrets.DOCKER_HUB_USERNAME }}/stellar-api'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/StellarApi/
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src/StellarApi/
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src/StellarApi/
    - name: Create Docker Image
      run: dotnet publish ./src/StellarApi/StellarApi.RestApi/StellarApi.RestApi.csproj /t:PublishContainer -r linux-x64
    - name: Change Image Tag
      run: docker tag stellar-api ${{ env.stellar_image }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Docker Push
      run: docker push ${{ env.stellar_image }}
    
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'prod'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.stellar_image }} 
      - name: Trigger Azure WebHook
        run: |
          curl -X POST $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.AZURE_WEBAPP_WEBHOOK_URL }}
        shell: bash    
